### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/manufacture#157]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] mrp_bom_dismantling
- [x] mrp_bom_note - By @bimajatiwijaya - #202 
- [ ] mrp_bom_product_details > mrp_bom_product_detail - By @bimajatiwijaya - #241  
- [ ] mrp_bom_reference_selection
- [x] mrp_calendar_view > mrp_repair_calendar_view - By @tafaRU - #177 
- [ ] mrp_industrial_design_bom
- [x] mrp_production_note - By @EBII - #174 
- [ ] mrp_production_partner_note - By @bimajatiwijaya - #204 
- [ ] mrp_production_properties - By @bimajatiwijaya - #209 
- [x] mrp_repair_discount - By @hurrinico - #180 
- [ ] mrp_sale_info - By @bimajatiwijaya - #201 
- [x] quality_control - By @SimoRubi - #239 
- [x] quality_control_stock - By @SimoRubi - #282
- [x] quality_control_mrp - By @SimoRubi - #283

**Comment by abelardo21** [comment]
Hola pedro buen día, estoy revisando el modulo mrp_production_partner_note y me interesa instalarlo en la versión 10, ya lo intente pero creo que el modulo no esta habilitado para la instalación aun, existe alguna manera de integrarlo a la versión 10? o se debe reprogramar?

Gracias de antemano por tu ayuda

**Comment by pedrobaeza** [comment]
Please speak only in English. You can see above that it's not migrated yet. Anyone can migrate it and contribute it in this repo.

**Comment by bimajatiwijaya** [comment]
Hello @pedrobaeza PR #201 mrp_sale_info created.

**Comment by bimajatiwijaya** [comment]
PR created mrp_bom_note #202

**Comment by bimajatiwijaya** [comment]
PR created mrp_product_details #203

**Comment by bimajatiwijaya** [comment]
mrp_production_properties #209

**Comment by SimoRubi** [comment]
quality_control_stock - By @SimoRubi https://github.com/OCA/manufacture/pull/282
quality_control_mrp - By @SimoRubi https://github.com/OCA/manufacture/pull/283
