### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/manufacture#226]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] mrp_auto_assign - By @lreficent - #270 
- [x] mrp_bom_component_menu - By @mreficent - #303
- [ ] mrp_bom_dismantling
- [x] mrp_bom_location - ~~by @mpanarin - in #254~~ - By @lreficent - ##285
- [ ] mrp_bom_note - By @agungrachmatulah - #265 
- [ ] mrp_bom_product_details
- [ ] mrp_bom_reference_selection
- [ ] mrp_industrial_design_bom
- [x] mrp_mto_with_stock - by @bodedra - in #255 
- [x] mrp_mto_with_stock_purchase - By @florian-dacosta - #302
- [ ] mrp_production_note
- [ ] mrp_production_partner_note
- [ ] mrp_production_properties
- [x] mrp_production_putaway_strategy - By @lreficent - #271
- [x] mrp_production_request - By @lreficent - #308
- [x] mrp_progress_button - By @jbeficent - #309
- [ ] mrp_project - By @SalahAdDin - #296 
- [ ] mrp_repair_calendar_view
- [x] mrp_repair_refurbish - By @lreficent - #321
- [x] mrp_sale_info - By @oihane - #294
- [x] quality_control - By @jhumfer - #298 
- [x] quality_control_issue - By @lreficent - #316
- [x] quality_control_mrp - By @NachoAlesLopez - #443 
- [x] quality_control_stock - By @NachoAlesLopez - #307 
- [x] quality_control_team - By @lreficent - #315

**Comment by bodedra** [comment]
mrp_mto_with_stock #255

**Comment by LoisRForgeFlow** [comment]
mrp_auto_assign https://github.com/OCA/manufacture/pull/270

**Comment by SalahAdDin** [comment]
mrp_project: https://github.com/OCA/manufacture/pull/296

**Comment by ProcessControl-JHF** [comment]
Hi! Why there isn't any **quality_control** module in the list? it's been moved to another branch or it's not longer needed. Thanks.

**Comment by pedrobaeza** [comment]
Because they were merged in 10.0 after the 11.0 branch (and this issue) creation, but no, we never remove modules from the list. If they are not needed, we strike-through them and comment the reason. I have added manually them.

**Comment by ProcessControl-JHF** [comment]
quality_control #298

**Comment by NachoAlesLopez** [comment]
quality_control_stock #307

**Comment by emagdalenaC2i** [comment]
@pedrobaeza you can check mrp_auto_assign - By @lreficent - #270 because it is merged
You can check quality_control_stock - By @NachoAlesLopez - #307 because it is merged
Please add to the list mrp_bom_component_menu - By @mreficent - #303 
Please add to the list mrp_mto_with_stock_purchase - By @florian-dacosta - #302 
Please add to the list mrp_production_putaway_strategy - By @lreficent - #271 
Please add to the list mrp_production_request - By @lreficent - #308 
Please add to the list mrp_progress_button - By @jbeficent - #309 
Please add to the list mrp_repair_refurbish - By @lreficent - #321
You can check mrp_sale_info - By @oihane - #294 
Please add to the list quality_control_issue - By @lreficent - #316 
Please add to the list quality_control_team - By @lreficent - #315

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, check mrp_bom_component_menu - By @mreficent - #303 because it is merged
check mrp_mto_with_stock_purchase - By @florian-dacosta - #302 because it is merged
check mrp_production_putaway_strategy - By @lreficent - #271 because it is merged
check mrp_production_request - By @lreficent - #308 because it is merged
check mrp_progress_button - By @jbeficent - #309 because it is merged
check mrp_repair_refurbish - By @lreficent - #321 because it is merged
check quality_control_issue - By @lreficent - #316 because it is merged
check quality_control_team - By @lreficent - #315 because it is merged

**Comment by NachoAlesLopez** [comment]
quality_control_mrp: #443

**Comment by voronind** [comment]
What about `mrp_production_hierarchy` module?
