### ISSUE TITLE
Roadmap of the Master Production Schedule

### ISSUE THREAD

**Issue by max3903** [OCA/manufacture#24]
The goal of this issue is to provide a roadmap for the Master Production Schedule module of Odoo.
# Version 0.1 (15k)
- [ ] Modeling of the MPS using sale and stock procurements (MPS input) and the Odoo scheduler to generate virtual manufacturing orders and purchase orders.
- [ ] Workflow: Draft, Planned, Confirmed, Done.
  - Planned: the scheduler has been run and the table is filled in
  - Confirmed: Manufacturing orders and purchases orders have been created in draft.
# Version 0.2 (5k)
- [ ] Provide a table like this one:

| Quantities | Period 1 | Period 2 | Period 3 |
| --- | --- | --- | --- |
| Initial Stock | 100 | 50 |  |
| Production | 50 / 90 | real / planned |  |
| Purchase | 5 / 10 | real / planned |  |
| Sales | 100 / 150 | real / planned |  |
| Final Stock | 50 | planned |  |
# Version 0.3 (15k)
- [ ] Add machines, configurations, operators and human resources
- [ ] Replace the Odoo Scheduler with a finite capacity scheduler. It will generate an exception or a purchase order with the quantity exceeding the production capacity.
# Version 0.4 (10k)
- [ ] Allow to use additional constraints within the scheduler: maintenance, working schedule
# Version 0.5 (20k)
- [ ] Gantt / Calendar views
- [ ] Reporting: Planned vs Actual comparison
