### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/manufacture#41]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] mrp_production_properties
- [x] mrp_bom_note - https://github.com/OCA/manufacture/pull/73
- [ ] mrp_calendar_view - By @nicomacr - #168 
- [x] mrp_production_note
- [ ] mrp_bom_product_details
- [ ] mrp_bom_reference_selection
- [ ] mrp_industrial_design_bom
- [ ] mrp_produce_uos
- [ ] mrp_bom_version - https://github.com/OCA/manufacture/pull/105
- [x] ~~mrp_hook~~ - Hooks already in core
- [ ] mrp_operations_extension 
- [ ] mrp_operations_project
- [ ] mrp_operations_time_control
- [X] mrp_production_partner_note - https://github.com/OCA/manufacture/pull/75
- [ ] mrp_production_estimated_cost
- [ ] mrp_production_real_cost
- [ ] mrp_project
- [x] mrp_sale_info - https://github.com/OCA/manufacture/pull/92
- [ ] quality_control - By @lreficent - #198 
- [ ] quality_control_mrp
- [ ] quality_control_stock

**Comment by JayVora-SerpentCS** [comment]
#100  for quality_control\* modules, work in progress

**Comment by pedrobaeza** [comment]
Thanks, @JayVora-SerpentCS, please migrate only one module per PR.

**Comment by thomaspaulb** [comment]
@pedrobaeza Can we cross off mrp_hook from this list because of [this](https://github.com/odoo/odoo/commit/fbc66b29e347e0856215fdd39e33b96ed1a1b79f)?

**Comment by pedrobaeza** [comment]
Done
