### ISSUE TITLE
[RFC][14.0] 🎪 Manufacturing Cost and Variance Analysis 

### ISSUE THREAD

**Issue by dreispt** [OCA/manufacture#565]
Manufacturing operations incur in costs.
We want to be able to track those costs in near real time. This is especially important to manufacturing orders with a long cycle time, spanning for multiple months.

Additionally, manufacturing operation can incur in several cost types. For example, labor, perishable tooling, overhead, etc. This feature allows to generate cost records for all the different cost types.

Feature breakdown:
- [ ] (A) #569 Materials - track costs. PR #573 
  - [x] Data model
  - [ ] Business logic: generate Analytic Items on MO Stock reservation
- [ ] (B) #568 Materials - initial estimates and variance analysis. PR #574
  - [x] Data model
  - [ ] Business logic: trigger a snapshot of the estimated cost and quantity for each MO Components line.  
- [ ] (C) #570 Operations - track costs. PR #575
  - [x] Data model
  - [ ] Business logic: Create Analytic Item on new time log record is added to Work Order Time Tracking
- [ ] (D) #567 Operations - initial estimates and variance analysis. PR #576
  - [x] Data model
  - [ ] Business logic: Extend the MO Confirm logic creating estimate snapshot, to populate the Work Center Analytic Estimate snapshot, update the "Duration (Estimated)" field on Work Centers.

**Comment by dreispt** [comment]
Cc @Chandresh-SerpentCS

**Comment by dreispt** [comment]
Note: I'm working on related designs right now, and plan to deprecated this Issue soon, since these features will be fit in a different module organization.
I'll more details soon.

**Comment by dreispt** [comment]
This design was expanded and superseded by 
- (A) #569 Materials - track costs
- (B) #568 Materials - initial estimates and variance analysis
- (C) #570 Operations - track costs
- (D) #567 Operations - initial estimates and variance analysis

These should first be implemented with only the data structures and basic views, and on a second iteration implement the business logic and refined UI.

**Comment by Chandresh-SerpentCS** [comment]
> This design was expanded and superseded by
> 
> * (A) #569 Materials - track costs
> * (B) #568 Materials - initial estimates and variance analysis
> * (C) #570 Operations - track costs
> * (D) #567 Operations - initial estimates and variance analysis
> 
> These should first be implemented with only the data structures and basic views, and on a second iteration implement the business logic and refined UI.

@dreispt Please find the linked PR reference against the issues.

(A) #569 > Link with PR #573
(B) #568  > Link with PR #574 
(C) #570  > Link with PR #575 
(D) #567  > Link with PR #576

**Comment by rvalyi** [comment]
@dreispt  from what I checked, A, B, C and D are all implemented and merged. Can we close it then?

cc @renatonlima probably what we should use when we migrate from 12.0

**Comment by dreispt** [comment]
@rvalyi Yes, they should be.
