### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/manufacture#868]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] mrp_account_analytic - By @dreispt - #1087
- [x] mrp_attachment_mgmt - By @jdidderen-noviat - #1115
- [ ] mrp_bom_attribute_match - By @mymage - #933
- [x] mrp_bom_component_menu - By @florian-dacosta - #915
- [ ] mrp_bom_hierarchy
- [x] mrp_bom_location - By @mymage - #936
- [ ] mrp_bom_tracking
- [x] mrp_bom_version - By @kaycross - #1368
- [ ] mrp_finished_backorder_product
- [x] mrp_lot_number_propagation - By @bosd - #1060
- [x] mrp_multi_level - By @JoanSForgeFlow - #897
- [ ] mrp_multi_level_estimate
- [x] mrp_planned_order_matrix - By @JoanSForgeFlow - #898
- [x] mrp_production_grouped_by_product - By @HeliconiaSolutions - #1405
- [x] mrp_production_note - By @Du-ma - #1094
- [ ] mrp_production_putaway_strategy
- [x] mrp_production_quant_manual_assign - By @alexis-via - #890
- [ ] mrp_progress_button
- [x] mrp_restrict_lot - By @florian-dacosta - #904
- [x] mrp_subcontracting_bom_dual_use - By @victoralmau - #1209
- [x] mrp_subcontracting_partner_management - By @victoralmau - #1233
- [x] mrp_unbuild_valuation_layer_link - By @JasminSForgeFlow - #1117
- [x] mrp_warehouse_calendar - By @JoanSForgeFlow - #895
- [x] mrp_workcenter_dashboard - By @rvalyi - #1661
- [ ] mrp_workorder_sequence
- [x] nobump - By @giarve - #1431
- [x] quality_control_mrp_oca - By @oihane - #1323
- [x] quality_control_oca - By @mymage - #923
- [x] quality_control_stock_oca - By @victoralmau - #1219

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by mymage** [comment]
I will migrate:
- quality_control_oca #923
- mrp_bom_attribute_match #933
- mrp_bom_hierarchy #935
- mrp_bom_location #936

**Comment by etoimene** [comment]
Anybody working on quality_control_stock_oca?
https://github.com/OCA/manufacture/tree/14.0/quality_control_stock_oca
Why is it not listed in "modules to migrate"?

**Comment by angelmoya** [comment]
@etoimene I'm working on quality_control_oca_stock_oca... is not on list because was not migrate to version 16.0

**Comment by jvpascual** [comment]
I'm working on mrp_workorder_sequence 
#1049

**Comment by bosd** [comment]
mrp_lot_number_propagation in #1060

**Comment by Du-ma** [comment]
`mrp_production_note` >> #1094

**Comment by ghost** [comment]
product_mrp_info -> https://github.com/OCA/manufacture/pull/1113
mrp_bom_hierarchy -> https://github.com/OCA/manufacture/pull/1114
mrp_attachment_mgmt -> https://github.com/OCA/manufacture/pull/1115

**Comment by SilvioC2C** [comment]
Migrating mrp_tag in https://github.com/OCA/manufacture/pull/1194
